// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7yuo3I_a-QsWyitqoB3WWQAwa6Bc1zQ',
    appId: '1:399605296427:web:ff30364b8fe8d208c3696e',
    messagingSenderId: '399605296427',
    projectId: 'pedidos-ropa-cerug',
    authDomain: 'pedidos-ropa-cerug.firebaseapp.com',
    storageBucket: 'pedidos-ropa-cerug.firebasestorage.app',
    measurementId: 'G-RP44ZSJ4PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7yuo3I_a-QsWyitqoB3WWQAwa6Bc1zQ',
    appId: '1:399605296427:android:ff30364b8fe8d208c3696e',
    messagingSenderId: '399605296427',
    projectId: 'pedidos-ropa-cerug',
    storageBucket: 'pedidos-ropa-cerug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7yuo3I_a-QsWyitqoB3WWQAwa6Bc1zQ',
    appId: '1:399605296427:ios:ff30364b8fe8d208c3696e',
    messagingSenderId: '399605296427',
    projectId: 'pedidos-ropa-cerug',
    storageBucket: 'pedidos-ropa-cerug.firebasestorage.app',
    iosBundleId: 'com.mycompany.pedidosropamatias',
  );
}
