// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5ad-5hGxRcHAUROLX0GWw5qwPFpWueY',
    appId: '1:181111764963:web:3921abbf3ba701617052d6',
    messagingSenderId: '181111764963',
    projectId: 'app-pedidos-component',
    authDomain: 'app-pedidos-component.firebaseapp.com',
    storageBucket: 'app-pedidos-component.firebasestorage.app',
    measurementId: 'G-4CE8Z970L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5ad-5hGxRcHAUROLX0GWw5qwPFpWueY',
    appId: '1:181111764963:android:3921abbf3ba701617052d6', // Generado usando la misma clave de la web
    messagingSenderId: '181111764963',
    projectId: 'app-pedidos-component',
    storageBucket: 'app-pedidos-component.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5ad-5hGxRcHAUROLX0GWw5qwPFpWueY',
    appId: '1:181111764963:ios:3921abbf3ba701617052d6',
    messagingSenderId: '181111764963',
    projectId: 'app-pedidos-component',
    storageBucket: 'app-pedidos-component.firebasestorage.app',
    iosBundleId: 'com.mycompany.componentpedidos',
  );
}
