// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRrSjQja8k9Vj2IJXQcI-MHjPFP7HfrA',
    appId: '1:308853230269:web:0a8905528009fc15aa85d4',
    messagingSenderId: '308853230269',
    projectId: 'app-pedidos-component-63dcf',
    authDomain: 'app-pedidos-component-63dcf.firebaseapp.com',
    storageBucket: 'app-pedidos-component-63dcf.firebasestorage.app',
    measurementId: 'G-SFC61VSFJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRrSjQja8k9Vj2IJXQcI-MHjPFP7HfrA',
    appId: '1:308853230269:android:0a8905528009fc15aa85d4', // Generado usando la misma clave de la web
    messagingSenderId: '308853230269',
    projectId: 'app-pedidos-component-63dcf',
    storageBucket: 'app-pedidos-component-63dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRrSjQja8k9Vj2IJXQcI-MHjPFP7HfrA',
    appId: '1:308853230269:ios:0a8905528009fc15aa85d4',
    messagingSenderId: '308853230269',
    projectId: 'app-pedidos-component-63dcf',
    storageBucket: 'app-pedidos-component-63dcf.firebasestorage.app',
    iosBundleId: 'com.mycompany.componentpedidos',
  );
}
